services:
  devopsDb:
    container_name: devopsDb
    image: postgres
    restart: unless-stopped
    env_file: ./.env.prod
    environment:
      POSTGRES_USER: sidof
      POSTGRES_PASSWORD: sidof1/@
      PGDATA: /data/postgres
    volumes:
      - networkDevops:/data/postgres
    ports:
      - 5434:5432
    networks:
      - networkDevops

 

networks:
  networkDevops:
    driver: bridge
volumes:
  networkDevops: