services:
  devopsDb:
    container_name: devopsDb
    image: postgres
    restart: unless-stopped
    env_file: ./.env.prod
    environment:
      POSTGRES_USER: sidof
      POSTGRES_PASSWORD: sidof1/@
      PGDATA: /data/postgres
    volumes:
      - networkDevops:/data/postgres
    ports:
      - 5432:5432
    networks:
      - networkDevops

  devops-skills-api:
    container_name: devops-skills-api
    build:
      context: .
      args:
        CONTAINER_PORT: 8083
    image: dountio/devops-skills-api:latest
    depends_on:
      - devopsDb
    restart: unless-stopped
    env_file: ./.env.prod
    ports:
      - 80:8083

    networks:
      - networkDevops

networks:
  networkDevops:
    driver: bridge
volumes:
  networkDevops: