services:
  school_app_db:
    container_name: school_app_db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sidof
      POSTGRES_PASSWORD: sidof1/@
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - 5433:5432
    expose:
      - 5432
    networks:
      - db

  api_school_app:
    depends_on:
      - school_app_db
    container_name: api_school_app
    build:
      context: .
      args:
        CONTAINER_PORT: ${CONTAINER_PORT}
    image: api_school_app:v1
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${SERVER_PORT}:${CONTAINER_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:postgresql://school_app_db:5432/dbschool",
            "spring.datasource.username" : "sidof",
            "spring.datasource.password" : "sidof1/@",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    networks:
      - db


networks:
  db:
    driver: bridge
volumes:
  db: