#SERVER
SERVER_PORT: 80
CONTAINER_PORT: 80
#PROFILE
ACTIVE_PROFILE: prod

#DATABASE
POSTGRES_USER: sidof
POSTGRES_PASSWORD: sidof1/@
POSTGRES_DATABASE: dbschool
POSTGRES_PORT: 5332
POSTGRES_HOST: localhost



