#SERVER
SERVER_PORT: 8083
CONTAINER_PORT: 8083
#PROFILE
ACTIVE_PROFILE: dev

#DATABASE
POSTGRES_USER: sidof
POSTGRES_PASSWORD: sidof1/@
POSTGRES_DATABASE: dbschool
POSTGRES_HOST: localhost
POSTGRES_DOCKER_PORT: 5434




