apiVersion: v1
kind: Service
metadata:
  name: schoolapi-service
spec:
  type: NodePort
  selector:
    app: schoolapi
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
    nodePort: 30001
