apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolapi
  labels:
    app: schoolapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schoolapi
  template:
    metadata:
      labels:
        app: schoolapi
    spec:
      containers:
      - name: schoolapi
        image: dountio/school:v1
        ports:
        - containerPort: 8083
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-url
