name: devOps on student app

on:
  push:
    branches:
      - deployment
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy gitHub action for beginner
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Maven Unit test
        run: mvn -B test --file pom.xml

      - name: Clean and Build the Application
        run: |
            mvn clean
            mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
            context: .
            dockerfile: Dockerfile
            push: false
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops-skills-api:v1

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to docker image on DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops-skills-api:v1

